#
# Blog Settings
#
author: Semih Kırdinli
description: ...ve düşünceleri
url: https://semihkirdinli.wordpress.com/
title: Semih Kırdinli
subtitle: ...ve düşünceleri
gravatar_url: https://2.gravatar.com/avatar/cdf546b601bf29a7eb4ca777544d11cd
subscribe_rss: https://semihkirdinli.wordpress.com/feed/

# Github repositories
github_user: haacked
github_repo_url: https://github.com/Haacked/haacked.com/

# Twitter
twitter_user: haacked
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: haacked
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-177588-1

kramdown:
  hard_wrap: true

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate