#
# Blog Settings
#
author: Semih Kırdinli
description: Semih Kırdinli © ...ve düşünceleri
url: http://semihkirdinli.github.io
>>>>>>> origin/master
title: Semih Kırdinli ⓒⓔ 
subtitle: ...ve düşünceleri
gravatar_url: https://tr.gravatar.com/userimage/4966509/ad4620408efa538c105cd45c70a2a131.jpg?size=200
subscribe_rss: https://semihkirdinli.wordpress.com/feed/

# Github repositories
github_user: semihkirdinli
github_repo_url: https://github.com/semihkirdinli/semihkirdinli.github.io/

# Twitter
twitter_user: skirdinli
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: skirdinli
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-177588-1

kramdown:
  hard_wrap: true

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
